"""Copy validated chapter code into the `gpt2moe` package.

The course builds one package, chapter after chapter. After the tests of a
chapter pass, this script copies your `exercise.py` into `gpt2moe/`. The next
chapter imports from the package, so it imports your own code.

    uv run python scripts/promote.py ch04
    uv run python scripts/promote.py ch04 --from-solution
"""

import argparse
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CHAPTERS = ROOT / "chapters"
PACKAGE = ROOT / "gpt2moe"


def find_chapter(prefix: str) -> Path:
    """Find the chapter directory that starts with `prefix`, for example ch04."""
    matches = sorted(p for p in CHAPTERS.iterdir() if p.is_dir() and p.name.startswith(prefix))
    if not matches:
        available = ", ".join(sorted(p.name for p in CHAPTERS.iterdir() if p.is_dir()))
        sys.exit(f"No chapter starts with {prefix!r}. Available: {available}")
    if len(matches) > 1:
        sys.exit(f"{prefix!r} is ambiguous: {', '.join(p.name for p in matches)}")
    return matches[0]


def module_name(chapter: Path) -> str:
    """Get the destination module name. ch04_attention becomes attention.py."""
    return chapter.name.split("_", 1)[1]


def tests_pass(chapter: Path) -> bool:
    """Run the tests of one chapter against the exercise code."""
    print(f"Run the tests of {chapter.name} ...")
    env = os.environ.copy()
    env["MOE_TARGET"] = "exercise"
    result = subprocess.run(
        [sys.executable, "-m", "pytest", str(chapter), "-q"],
        cwd=ROOT,
        env=env,
    )
    return result.returncode == 0


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("chapter", help="chapter prefix, for example ch04")
    parser.add_argument(
        "--from-solution",
        action="store_true",
        help="promote the reference code instead of yours, and skip the tests",
    )
    args = parser.parse_args()

    chapter = find_chapter(args.chapter)
    source_name = "solution" if args.from_solution else "exercise"
    source = chapter / f"{source_name}.py"
    if not source.exists():
        sys.exit(f"{source} does not exist")

    if not args.from_solution and not tests_pass(chapter):
        sys.exit(
            f"\nThe tests of {chapter.name} fail, so nothing moved.\n"
            f"Correct {source}, or use --from-solution to continue with the reference code."
        )

    PACKAGE.mkdir(exist_ok=True)
    destination = PACKAGE / f"{module_name(chapter)}.py"
    header = (
        f'"""Promoted from chapters/{chapter.name}/{source_name}.py.\n\n'
        f"Do not edit this file. Edit the chapter, then promote it again.\n"
        f'"""\n\n'
    )
    destination.write_text(header + source.read_text())
    print(f"OK. {chapter.name}/{source_name}.py is now gpt2moe/{destination.name}")


if __name__ == "__main__":
    main()
